version: "3.8"
services:
  db:
    build: ../dolt-builds
  sysbench:
    build: ../sysbench
    environment:
      - DOLT_COMMITTISH
      - SYSBENCH_TESTS
      - TEST_USERNAME
      - DB_HOST=db
    volumes:
      - ../python:/python
      - ../output:/output
    depends_on:
      - db
