version: "3.8"
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
  sysbench:
    build: ../sysbench
    environment:
      - SYSBENCH_TESTS
      - TEST_USERNAME
      - DB_HOST=db
    volumes:
      - ../python:/python
      - ../output:/output
    depends_on:
      - db
